global:
  cicle_timeout: 10
  proxy_checks_parralel: 100

dns_checks:
  - dns_servers:
      - 8.8.8.8
      - 192.168.0.1
    domains:
      - google.com
      - yahoo.com
      - microsoft.com

simple_checks:
  - domain_name: node1.example.com # check all IP addresses resolved by name
    port: 22
    filter_resolve: '<value>' # value = '' => check all addresses (ipv4 and ipv6);
                              # value = 'ipv4'
                              # value = 'ipv6'

http_checks:
  - domain_name: some.example.com
    status_code: 301                            # if status code is 301,302,307,308, then target_data searchs in header "Location"
    target_data: 'https://some.example.com'     
  - domain_name: some2.example.com
    check_id: 'asd' # uniq for label
    scheme: https # default is http
    port: 443 # default is:
              #    80 for scheme='http'
              #   443 for scheme='https'
    follow_redirects: True # default: False
    timeout: 10 # in seconds for response wait; default: 3
    status_code: 200 # default: 200
    target_scheme: https # default: undefined ==> after all redirects target url must be in 'target_scheme' for success check
    target_data: 'preload' # default: ''
                           # if response code is not redirect code (301,302,307,308) --> target_data searches in response body
    basic_auth:            # default undefined
      username: 'test'     
      password: 'qweqweqwe'

proxy_checks:
  - proxy_ips:
      - 192.168.20.2
      - 192.168.20.3
    add_headers: # for request
      - 'Header_name: Header_value'
    add_labels:   ## For metrics output
      - 'MegaLabel: 3'
    proxy_port: 3128      # Port for all defined proxies
    proxy_protocol: 'http|socks5'
    proxy_auth:           # Cred for proxies (all IPs checks for all auth creds)
      - user: user1
        password: pass1
        add_headers:
          - 'Header2: Value2'
        label_id: 'check via user1' # uniq for label
      - user: user2
        password: pass2
        label_id: 'check via user2'
        add_labels:   ## For metrics output on the some auth kreds
          - 'Under_cred_label: 42'
    url: 'http://google.com'  # which url must be checked via forward-proxy
    status_code: <200|ANY>    # status code for success check (default: 200)
    timeout: 10               # timeout for response wait, default: 3